---@meta

-- Lmaobox Lua API: BitBuffer - Lmaobox Lua
-- Auto-generated from: https://lmaobox.net/lua/Lua_Classes/BitBuffer/
-- Path: Lua_Classes/BitBuffer
-- Last updated: 2025-12-05T11:09:57.186Z

---@class BitBuffer
---@return any
---@field BitBuffer fun(self: BitBuffer): any
---@return number
---@field GetDataBitsLength fun(self: BitBuffer): number
---@return number
---@field GetDataBytesLength fun(self: BitBuffer): number
---@return any
---@field Reset fun(self: BitBuffer): any
---@return any
---@field ReadByte fun(self: BitBuffer): any
---@return any
---@field ReadBit fun(self: BitBuffer): any
---@param bitLength integer
---@return number
---@field ReadFloat fun(self: BitBuffer, bitLength: integer): number
---@param bitLength integer
---@return number
---@field ReadInt fun(self: BitBuffer, bitLength: integer): number
---@param maxlen integer
---@return string
---@field ReadString fun(self: BitBuffer, maxlen: integer): string
---@return any
---@field GetCurBit fun(self: BitBuffer): any
---@param bit integer
---@field SetCurBit fun(self: BitBuffer, bit: integer)
---@param bit integer
---@return any
---@field WriteBit fun(self: BitBuffer, bit: integer): any
---@param byte integer
---@return any
---@field WriteByte fun(self: BitBuffer, byte: integer): any
---@param str string
---@return string
---@field WriteString fun(self: BitBuffer, str: string): string
---@param int integer
---@param bitLength integer
---@return number
---@field WriteInt fun(self: BitBuffer, int: integer, bitLength: integer): number
---@param value number
---@param bitLength integer
---@return number
---@field WriteFloat fun(self: BitBuffer, value: number, bitLength: integer): number
---@return any
---@field Delete fun(self: BitBuffer): any
local BitBuffer = {}

