---@meta

-- Lmaobox Lua API: DrawModelContext - Lmaobox Lua
-- Auto-generated from: https://lmaobox.net/lua/Lua_Classes/DrawModelContext/
-- Path: Lua_Classes/DrawModelContext
-- Last updated: 2025-12-05T09:48:47.582Z

---@class DrawModelContext
---@return any
---@field Methods fun(self: DrawModelContext): any
---@return any
---@field Examples fun(self: DrawModelContext): any
---@return Entity|nil
---@field GetEntity fun(self: DrawModelContext): Entity|nil
---@return string
---@field GetModelName fun(self: DrawModelContext): string
---@return any
---@field ForcedMaterialOverride fun(self: DrawModelContext): any
---@return any
---@field DrawExtraPass fun(self: DrawModelContext): any
---@return any
---@field StudioSetColorModulation fun(self: DrawModelContext): any
---@return any
---@field StudioSetAlphaModulation fun(self: DrawModelContext): any
---@return any
---@field SetColorModulation fun(self: DrawModelContext): any
---@return any
---@field SetAlphaModulation fun(self: DrawModelContext): any
---@return any
---@field DepthRange fun(self: DrawModelContext): any
---@return any
---@field SuppressEngineLighting fun(self: DrawModelContext): any
---@return any
---@field Execute fun(self: DrawModelContext): any
---@return boolean
---@field IsDrawingAntiAim fun(self: DrawModelContext): boolean
---@return boolean
---@field IsDrawingBackTrack fun(self: DrawModelContext): boolean
---@return boolean
---@field IsDrawingGlow fun(self: DrawModelContext): boolean
local DrawModelContext = {}

