---@meta

-- Lmaobox Lua API: Entity - Lmaobox Lua
-- Auto-generated from: https://lmaobox.net/lua/Lua_Classes/Entity/
-- Path: Lua_Classes/Entity
-- Last updated: 2025-12-05T11:20:20.611Z

---@class Entity
---@return boolean
---@field IsValid fun(self: Entity): boolean
---@return string
---@field GetName fun(self: Entity): string
---@return any
---@field GetClass fun(self: Entity): any
---@return number
---@field GetIndex fun(self: Entity): number
---@return any
---@field GetTeamNumber fun(self: Entity): any
---@return Vector3
---@field GetAbsOrigin fun(self: Entity): Vector3
---@param origin Vector3
---@return Vector3
---@field SetAbsOrigin fun(self: Entity, origin: Vector3): Vector3
---@return Vector3
---@field GetAbsAngles fun(self: Entity): Vector3
---@param angles Vector3
---@return Vector3
---@field SetAbsAngles fun(self: Entity, angles: Vector3): Vector3
---@return any
---@field GetMins fun(self: Entity): any
---@return any
---@field GetMaxs fun(self: Entity): any
---@return any
---@field GetHealth fun(self: Entity): any
---@return any
---@field GetMaxHealth fun(self: Entity): any
---@return any
---@field GetMoveChild fun(self: Entity): any
---@return any
---@field GetMovePeer fun(self: Entity): any
---@return boolean
---@field IsPlayer fun(self: Entity): boolean
---@return boolean
---@field IsWeapon fun(self: Entity): boolean
---@return boolean
---@field IsAlive fun(self: Entity): boolean
---@return Vector3
---@field EstimateAbsVelocity fun(self: Entity): Vector3
---@return any
---@field GetMoveType fun(self: Entity): any
---@return any
---@field HitboxSurroundingBox fun(self: Entity): any
---@return Entity|nil
---@field EntitySpaceHitboxSurroundingBox fun(self: Entity): Entity|nil
---@param boneMask integer
---@param currentTime number
---@field SetupBones fun(self: Entity, boneMask: integer, currentTime: number)
---@param currentTime number
---@return any
---@field GetHitboxes fun(self: Entity, currentTime: number): any
---@param modelPath string
---@field SetModel fun(self: Entity, modelPath: string)
---@return any
---@field GetModel fun(self: Entity): any
---@return any
---@field ShouldDraw fun(self: Entity): any
---@return any
---@field GetInvisibility fun(self: Entity): any
---@param value float
---@field SetInvisibility fun(self: Entity, value: float)
---@param drawFlags integer
---@return any
---@field DrawModel fun(self: Entity, drawFlags: integer): any
---@return any
---@field Release fun(self: Entity): any
---@return boolean
---@field IsDormant fun(self: Entity): boolean
---@return any
---@field ToInventoryItem fun(self: Entity): any
---@param name string
---@param defaultValue number
---@return number
---@field AttributeHookFloat fun(self: Entity, name: string, defaultValue: number): number
---@param name string
---@param defaultValue integer
---@return number
---@field AttributeHookInt fun(self: Entity, name: string, defaultValue: integer): number
---@return number
---@field GetPropFloat fun(self: Entity): number
---@return number
---@field GetPropInt fun(self: Entity): number
---@return any
---@field GetPropBool fun(self: Entity): any
---@return string
---@field GetPropString fun(self: Entity): string
---@return Vector3
---@field GetPropVector fun(self: Entity): Vector3
---@return Entity|nil
---@field GetPropEntity fun(self: Entity): Entity|nil
---@param value number
---@return number
---@field SetPropFloat fun(self: Entity, value: number): number
---@param value integer
---@return number
---@field SetPropInt fun(self: Entity, value: integer): number
---@param value bool
---@field SetPropBool fun(self: Entity, value: bool)
---@param value Entity
---@return Entity|nil
---@field SetPropEntity fun(self: Entity, value: Entity): Entity|nil
---@param value Vector3
---@return Vector3
---@field SetPropVector fun(self: Entity, value: Vector3): Vector3
---@return number
---@field GetPropDataTableFloat fun(self: Entity): number
---@return any
---@field GetPropDataTableBool fun(self: Entity): any
---@return number
---@field GetPropDataTableInt fun(self: Entity): number
---@return Entity|nil
---@field GetPropDataTableEntity fun(self: Entity): Entity|nil
---@param value number
---@param index integer
---@return number
---@field SetPropDataTableFloat fun(self: Entity, value: number, index: integer): number
---@param value integer
---@param index integer
---@field SetPropDataTableBool fun(self: Entity, value: integer, index: integer)
---@param value integer
---@param index integer
---@return number
---@field SetPropDataTableInt fun(self: Entity, value: integer, index: integer): number
---@param value Entity
---@param index integer
---@return Entity|nil
---@field SetPropDataTableEntity fun(self: Entity, value: Entity, index: integer): Entity|nil
---@param condition integer
---@return any
---@field InCond fun(self: Entity, condition: integer): any
---@param condition integer
---@param duration number
---@return any
---@field AddCond fun(self: Entity, condition: integer, duration: number): any
---@param condition integer
---@return any
---@field RemoveCond fun(self: Entity, condition: integer): any
---@return boolean
---@field IsCritBoosted fun(self: Entity): boolean
---@return any
---@field GetCritMult fun(self: Entity): any
---@return any
---@field GetCarryingRuneType fun(self: Entity): any
---@return any
---@field GetMaxBuffedHealth fun(self: Entity): any
---@param slot integer
---@return Entity|nil
---@field GetEntityForLoadoutSlot fun(self: Entity, slot: integer): Entity|nil
---@return boolean
---@field IsInFreezecam fun(self: Entity): boolean
---@return Vector3
---@field GetVAngles fun(self: Entity): Vector3
---@param vecAngles Vector3
---@return Vector3
---@field SetVAngles fun(self: Entity, vecAngles: Vector3): Vector3
---@return boolean
---@field IsShootingWeapon fun(self: Entity): boolean
---@return boolean
---@field IsMeleeWeapon fun(self: Entity): boolean
---@return boolean
---@field IsMedigun fun(self: Entity): boolean
---@return boolean
---@field CanRandomCrit fun(self: Entity): boolean
---@return any
---@field GetLoadoutSlot fun(self: Entity): any
---@return Entity|nil
---@field GetWeaponID fun(self: Entity): Entity|nil
---@return boolean
---@field IsViewModelFlipped fun(self: Entity): boolean
---@return Entity|nil
---@field GetWeaponData fun(self: Entity): Entity|nil
---@param player entity
---@param vecOffset Vector3
---@param bHitTeammates bool
---@param flEndDist number
---@return any
---@field GetProjectileFireSetup fun(self: Entity, player: entity, vecOffset: Vector3, bHitTeammates: bool, flEndDist: number): any
---@return Entity|nil
---@field GetWeaponProjectileType fun(self: Entity): Entity|nil
---@return Entity|nil
---@field GetWeaponSpread fun(self: Entity): Entity|nil
---@return any
---@field GetProjectileSpeed fun(self: Entity): any
---@return any
---@field GetProjectileGravity fun(self: Entity): any
---@return any
---@field GetProjectileSpread fun(self: Entity): any
---@return boolean
---@field CanCharge fun(self: Entity): boolean
---@return number
---@field GetChargeBeginTime fun(self: Entity): number
---@return number
---@field GetChargeMaxTime fun(self: Entity): number
---@return any
---@field GetCurrentCharge fun(self: Entity): any
---@return any
---@field GetSwingRange fun(self: Entity): any
---@return any
---@field DoSwingTrace fun(self: Entity): any
---@return any
---@field GetMedigunHealRate fun(self: Entity): any
---@return any
---@field GetMedigunHealingStickRange fun(self: Entity): any
---@return any
---@field GetMedigunHealingRange fun(self: Entity): any
---@param target Entity
---@return boolean
---@field IsMedigunAllowedToHealTarget fun(self: Entity, target: Entity): boolean
---@return any
---@field GetCritTokenBucket fun(self: Entity): any
---@return number
---@field GetCritCheckCount fun(self: Entity): number
---@return number
---@field GetCritSeedRequestCount fun(self: Entity): number
---@return any
---@field GetCurrentCritSeed fun(self: Entity): any
---@return number
---@field GetRapidFireCritTime fun(self: Entity): number
---@return number
---@field GetLastRapidFireCritCheckTime fun(self: Entity): number
---@return Entity|nil
---@field GetWeaponBaseDamage fun(self: Entity): Entity|nil
---@return any
---@field GetCritChance fun(self: Entity): any
---@param tokenBucket number
---@param critSeedRequestCount number
---@param critCheckCount number
---@return any
---@field GetCritCost fun(self: Entity, tokenBucket: number, critSeedRequestCount: number, critCheckCount: number): any
---@return any
---@field CalcObservedCritChance fun(self: Entity): any
---@param commandNumber integer
---@return boolean
---@field IsAttackCritical fun(self: Entity, commandNumber: integer): boolean
---@return Entity|nil
---@field GetWeaponDamageStats fun(self: Entity): Entity|nil
local Entity = {}

