---@meta

-- Lmaobox Lua API: GameEvent - Lmaobox Lua
-- Auto-generated from: https://lmaobox.net/lua/Lua_Classes/GameEvent/
-- Path: Lua_Classes/GameEvent
-- Last updated: 2025-12-05T11:09:57.230Z

---@class GameEvent
-- Returns the name of the event.
---@return any
---@field Methods fun(self: GameEvent): any
---@return any
---@field Examples fun(self: GameEvent): any
-- Returns the name of the event.
---@return string
---@field GetName fun(self: GameEvent): string
-- Returns the string value of the given field.
---@param fieldName string
---@return string
---@field GetString fun(self: GameEvent, fieldName: string): string
-- Returns the int value of the given field.
---@param fieldName string
---@return number
---@field GetInt fun(self: GameEvent, fieldName: string): number
-- Returns the float value of the given field.
---@param fieldName string
---@return number
---@field GetFloat fun(self: GameEvent, fieldName: string): number
-- Sets the string value of the given field.
---@param fieldName string
---@param value string
---@field SetString fun(self: GameEvent, fieldName: string, value: string)
-- Sets the int value of the given field.
---@param fieldName string
---@param value int
---@field SetInt fun(self: GameEvent, fieldName: string, value: int)
-- Sets the float value of the given field.
---@param fieldName string
---@param value float
---@field SetFloat fun(self: GameEvent, fieldName: string, value: float)
-- Sets the bool value of the given field.
---@param fieldName string
---@param value bool
---@field SetBool fun(self: GameEvent, fieldName: string, value: bool)
local GameEvent = {}

