---@meta

-- Lmaobox Lua API: PhysicsEnvironment - Lmaobox Lua
-- Auto-generated from: https://lmaobox.net/lua/Lua_Classes/PhysicsEnvironment/
-- Path: Lua_Classes/PhysicsEnvironment
-- Last updated: 2025-12-05T11:20:20.754Z

---@class PhysicsEnvironment
---@param gravity Vector3
---@field SetGravity fun(self: PhysicsEnvironment, gravity: Vector3)
---@return any
---@field GetGravity fun(self: PhysicsEnvironment): any
---@param airDensity float
---@field SetAirDensity fun(self: PhysicsEnvironment, airDensity: float)
---@return any
---@field GetAirDensity fun(self: PhysicsEnvironment): any
---@param deltaTime float
---@return any
---@field Simulate fun(self: PhysicsEnvironment, deltaTime: float): any
---@return boolean
---@field IsInSimulation fun(self: PhysicsEnvironment): boolean
---@return number
---@field GetSimulationTime fun(self: PhysicsEnvironment): number
---@return number
---@field GetSimulationTimestep fun(self: PhysicsEnvironment): number
---@param timestep float
---@return number
---@field SetSimulationTimestep fun(self: PhysicsEnvironment, timestep: float): number
---@return any
---@field GetActiveObjects fun(self: PhysicsEnvironment): any
---@return any
---@field ResetSimulationClock fun(self: PhysicsEnvironment): any
---@param collisionModel PhysicsCollisionModel
---@param surfacePropertyName string
---@param objectParams PhysicsObjectParameters
---@return any
---@field CreatePolyObject fun(self: PhysicsEnvironment, collisionModel: PhysicsCollisionModel, surfacePropertyName: string, objectParams: PhysicsObjectParameters): any
---@param object PhysicsObject
---@return any
---@field DestroyObject fun(self: PhysicsEnvironment, object: PhysicsObject): any
local PhysicsEnvironment = {}

