---@meta

-- Lmaobox Lua API: TempEntity - Lmaobox Lua
-- Auto-generated from: https://lmaobox.net/lua/Lua_Classes/TempEntity/
-- Path: Lua_Classes/TempEntity
-- Last updated: 2025-12-05T12:04:25.957Z

---@class TempEntity
---@return string
---@field GetNetworkName fun(self: TempEntity): string
---@return any
---@field Release fun(self: TempEntity): any
---@param dataUpdateType integer
---@return any
---@field PostDataUpdate fun(self: TempEntity, dataUpdateType: integer): any
---@return number
---@field GetPropFloat fun(self: TempEntity): number
---@return number
---@field GetPropInt fun(self: TempEntity): number
---@return any
---@field GetPropBool fun(self: TempEntity): any
---@return string
---@field GetPropString fun(self: TempEntity): string
---@return Vector3
---@field GetPropVector fun(self: TempEntity): Vector3
---@return Entity|nil
---@field GetPropEntity fun(self: TempEntity): Entity|nil
---@param value number
---@return number
---@field SetPropFloat fun(self: TempEntity, value: number): number
---@param value integer
---@return number
---@field SetPropInt fun(self: TempEntity, value: integer): number
---@param value bool
---@field SetPropBool fun(self: TempEntity, value: bool)
---@param value Entity
---@return Entity|nil
---@field SetPropEntity fun(self: TempEntity, value: Entity): Entity|nil
---@param value Vector3
---@return Vector3
---@field SetPropVector fun(self: TempEntity, value: Vector3): Vector3
---@return number
---@field GetPropDataTableFloat fun(self: TempEntity): number
---@return any
---@field GetPropDataTableBool fun(self: TempEntity): any
---@return number
---@field GetPropDataTableInt fun(self: TempEntity): number
---@return Entity|nil
---@field GetPropDataTableEntity fun(self: TempEntity): Entity|nil
---@param value number
---@param index integer
---@return number
---@field SetPropDataTableFloat fun(self: TempEntity, value: number, index: integer): number
---@param value integer
---@param index integer
---@field SetPropDataTableBool fun(self: TempEntity, value: integer, index: integer)
---@param value integer
---@param index integer
---@return number
---@field SetPropDataTableInt fun(self: TempEntity, value: integer, index: integer): number
---@param value Entity
---@param index integer
---@return Entity|nil
---@field SetPropDataTableEntity fun(self: TempEntity, value: Entity, index: integer): Entity|nil
local TempEntity = {}

