---@meta

-- Lmaobox Lua API: Trace - Lmaobox Lua
-- Auto-generated from: https://lmaobox.net/lua/Lua_Classes/Trace/
-- Path: Lua_Classes/Trace
-- Last updated: 2025-12-05T10:33:20.320Z

---@class Trace
-- Fields are non-modifiable.
---@return any
---@field Fields fun(self: Trace): any
-- More information can be found at Valve Wiki
---@return any
---@field Extra fun(self: Trace): any
---@return any
---@field Examples fun(self: Trace): any
-- number
---@return any
---@field fraction fun(self: Trace): any
-- Entity
---@return any
---@field entity fun(self: Trace): any
-- Vector3
---@return any
---@field plane fun(self: Trace): any
-- integer
---@return any
---@field contents fun(self: Trace): any
-- integer
---@return any
---@field hitbox fun(self: Trace): any
-- integer
---@return any
---@field hitgroup fun(self: Trace): any
-- boolean
---@return any
---@field allsolid fun(self: Trace): any
-- boolean
---@return any
---@field startsolid fun(self: Trace): any
-- Vector3
---@return any
---@field startpos fun(self: Trace): any
-- Vector3
---@return any
---@field endpos fun(self: Trace): any
local Trace = {}

