---@meta

-- Lmaobox Lua API: UserCmd - Lmaobox Lua
-- Auto-generated from: https://lmaobox.net/lua/Lua_Classes/UserCmd/
-- Path: Lua_Classes/UserCmd
-- Last updated: 2025-12-05T10:33:20.326Z

---@class UserCmd
-- Fields are modifiable directly.
---@return any
---@field Fields fun(self: UserCmd): any
-- Sets the view angles of the player.
---@return any
---@field Methods fun(self: UserCmd): any
---@return any
---@field Examples fun(self: UserCmd): any
-- integer
---@return any
---@field command_number fun(self: UserCmd): any
-- integer
---@return any
---@field tick_count fun(self: UserCmd): any
-- EulerAngles
---@return any
---@field viewangles fun(self: UserCmd): any
-- number
---@return any
---@field forwardmove fun(self: UserCmd): any
-- number
---@return any
---@field sidemove fun(self: UserCmd): any
-- number
---@return any
---@field upmove fun(self: UserCmd): any
-- integer (bits)
---@return any
---@field buttons fun(self: UserCmd): any
-- integer
---@return any
---@field impulse fun(self: UserCmd): any
-- integer
---@return any
---@field weaponselect fun(self: UserCmd): any
-- integer
---@return any
---@field weaponsubtype fun(self: UserCmd): any
-- integer
---@return any
---@field random_seed fun(self: UserCmd): any
-- integer
---@return any
---@field mousedx fun(self: UserCmd): any
-- integer
---@return any
---@field mousedy fun(self: UserCmd): any
-- boolean
---@return any
---@field hasbeenpredicted fun(self: UserCmd): any
-- boolean
---@return any
---@field sendpacket fun(self: UserCmd): any
-- Sets the view angles of the player.
---@return Vector3
---@field SetViewAngles fun(self: UserCmd): Vector3
-- returns: pitch, yaw, roll
---@return Vector3
---@field GetViewAngles fun(self: UserCmd): Vector3
-- Sets whether the command should be sent to the server or choked.
---@return any
---@field SetSendPacket fun(self: UserCmd): any
-- returns: sendpacket
---@return any
---@field GetSendPacket fun(self: UserCmd): any
-- Sets the buttons that are pressed.
---@return any
---@field SetButtons fun(self: UserCmd): any
-- returns: buttons
---@return any
---@field GetButtons fun(self: UserCmd): any
-- Sets the forward movement of the player.
---@return any
---@field SetForwardMove fun(self: UserCmd): any
-- returns: forwardmove
---@return any
---@field GetForwardMove fun(self: UserCmd): any
-- Sets the sideways movement of the player.
---@return any
---@field SetSideMove fun(self: UserCmd): any
-- returns: sidemove
---@return any
---@field GetSideMove fun(self: UserCmd): any
-- Sets the upward movement of the player.
---@return any
---@field SetUpMove fun(self: UserCmd): any
-- returns: upmove
---@return any
---@field GetUpMove fun(self: UserCmd): any
local UserCmd = {}

