---@meta

-- Lmaobox Lua API Type Definitions Index
--
-- All .d.lua files in this directory and subdirectories are automatically loaded
-- by the Lua Language Server when ${workspace}/types is included in Lua.workspace.library
--
-- File organization:
-- - lmaobox.d.lua - Core API type definitions (client, draw, engine, entities, etc.)
-- - constants/ - All constant definitions organized by category
-- - entity_props/ - All entity property definitions organized by entity type
--
-- Auto-updating to latest Lua 5.4.x syntax
-- API Documentation: http://lmaobox.net/lua/sitemap.xml
--
-- To update type definitions:
-- 1. Check http://lmaobox.net/lua/sitemap.xml for latest API
-- 2. Update the relevant type definition file(s)
-- 3. Reload VS Code window for changes to take effect
-- 4. Or run: node automations/update-types.js (auto-update script)
