---@meta

-- Constants: E_FileAttribute
-- Auto-generated from: https://lmaobox.net/lua/Lua_Constants/
-- Last updated: 2025-12-05T11:09:58.747Z

---@type any
FILE_ATTRIBUTE_READONLY = 0x1

---@type any
FILE_ATTRIBUTE_HIDDEN = 0x2

---@type any
FILE_ATTRIBUTE_SYSTEM = 0x4

---@type any
FILE_ATTRIBUTE_DIRECTORY = 0x10

---@type any
FILE_ATTRIBUTE_ARCHIVE = 0x20

---@type any
FILE_ATTRIBUTE_DEVICE = 0x40

---@type any
FILE_ATTRIBUTE_NORMAL = 0x80

---@type any
FILE_ATTRIBUTE_TEMPORARY = 0x100

---@type any
FILE_ATTRIBUTE_SPARSE_FILE = 0x200

---@type any
FILE_ATTRIBUTE_REPARSE_POINT = 0x400

---@type any
FILE_ATTRIBUTE_COMPRESSED = 0x800

---@type any
FILE_ATTRIBUTE_OFFLINE = 0x1000

---@type any
FILE_ATTRIBUTE_NOT_CONTENT_INDEXED = 0x2000

---@type any
FILE_ATTRIBUTE_ENCRYPTED = 0x4000

---@type any
FILE_ATTRIBUTE_INTEGRITY_STREAM = 0x8000

---@type any
FILE_ATTRIBUTE_VIRTUAL = 0x10000

---@type any
FILE_ATTRIBUTE_NO_SCRUB_DATA = 0x20000

---@type any
FILE_ATTRIBUTE_RECALL_ON_OPEN = 0x40000

---@type any
FILE_ATTRIBUTE_PINNED = 0x80000

---@type any
FILE_ATTRIBUTE_UNPINNED = 0x100000

---@type any
FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS = 0x400000

---@type any
INVALID_FILE_ATTRIBUTES = 0xFFFFFFFF

