---@meta

-- Constants: E_KillEffect
-- Auto-generated from: https://lmaobox.net/lua/Lua_Constants/
-- Last updated: 2025-12-05T11:44:48.754Z

---@type any
TF_CUSTOM_AIM_HEADSHOT = 1

---@type any
TF_CUSTOM_BACKSTAB = 2

---@type any
TF_CUSTOM_BURNING = 3

---@type any
TF_CUSTOM_WRENCH_FIX = 4

---@type any
TF_CUSTOM_MINIGUN = 5

---@type any
TF_CUSTOM_SUICIDE = 6

---@type any
TF_CUSTOM_TAUNT_HADOUKEN = 7

---@type any
TF_CUSTOM_BURNING_FLARE = 8

---@type any
TF_CUSTOM_TAUNT_HIGH_NOON = 9

---@type any
TF_CUSTOM_TAUNT_GRAND_SLAM = 10

---@type any
TF_CUSTOM_PENETRATE_MY_TEAM = 11

---@type any
TF_CUSTOM_PENETRATE_ALL_PLAYERS = 12

---@type any
TF_CUSTOM_TAUNT_FENCING = 13

---@type any
TF_CUSTOM_PENETRATE_AIM_HEADSHOT = 14

---@type any
TF_CUSTOM_TAUNT_ARROW_STAB = 15

---@type any
TF_CUSTOM_TELEFRAG = 16

---@type any
TF_CUSTOM_BURNING_ARROW = 17

---@type any
TF_CUSTOM_FLYINGBURN = 18

---@type any
TF_CUSTOM_PUMPKIN_BOMB = 19

---@type any
TF_CUSTOM_DECAPITATION = 20

---@type any
TF_CUSTOM_TAUNT_GRENADE = 21

---@type any
TF_CUSTOM_BASEBALL = 22

---@type any
TF_CUSTOM_CHARGE_IMPACT = 23

---@type any
TF_CUSTOM_TAUNT_BARBARIAN_SWING = 24

---@type any
TF_CUSTOM_AIR_STICKY_BURST = 25

---@type any
TF_CUSTOM_DEFENSIVE_STICKY = 26

---@type any
TF_CUSTOM_PICKAXE = 27

---@type any
TF_CUSTOM_ROCKET_DIRECTHIT = 28

---@type any
TF_CUSTOM_TAUNT_UBERSLICE = 29

---@type any
TF_CUSTOM_PLAYER_SENTRY = 30

---@type any
TF_CUSTOM_STANDARD_STICKY = 31

---@type any
TF_CUSTOM_SHOTGUN_REVENGE_CRIT = 32

---@type any
TF_CUSTOM_TAUNT_ENGINEER_SMASH = 33

---@type any
TF_CUSTOM_BLEEDING = 34

---@type any
TF_CUSTOM_GOLD_WRENCH = 35

---@type any
TF_CUSTOM_CARRIED_BUILDING = 36

---@type any
TF_CUSTOM_COMBO_PUNCH = 37

---@type any
TF_CUSTOM_TAUNT_ENGINEER_ARM = 38

---@type any
TF_CUSTOM_FISH_KILL = 39

---@type any
TF_CUSTOM_TRIGGER_HURT = 40

---@type any
TF_CUSTOM_DECAPITATION_BOSS = 41

---@type any
TF_CUSTOM_STICKBOMB_EXPLOSION = 42

---@type any
TF_CUSTOM_AEGIS_ROUND = 43

---@type any
TF_CUSTOM_FLARE_EXPLOSION = 44

---@type any
TF_CUSTOM_BOOTS_STOMP = 45

---@type any
TF_CUSTOM_PLASMA = 46

---@type any
TF_CUSTOM_PLASMA_CHARGED = 47

---@type any
TF_CUSTOM_PLASMA_GIB = 48

---@type any
TF_CUSTOM_PRACTICE_STICKY = 49

---@type any
TF_CUSTOM_EYEBALL_ROCKET = 50

---@type any
TF_CUSTOM_AIM_HEADSHOT_DECAPITATION = 51

---@type any
TF_CUSTOM_TAUNT_ARMAGEDDON = 52

---@type any
TF_CUSTOM_FLARE_PELLET = 53

---@type any
TF_CUSTOM_CLEAVER = 54

---@type any
TF_CUSTOM_CLEAVER_CRIT = 55

---@type any
TF_CUSTOM_SAPPER_RECORDER_DEATH = 56

---@type any
TF_CUSTOM_MERASMUS_PLAYER_BOMB = 57

---@type any
TF_CUSTOM_MERASMUS_GRENADE = 58

---@type any
TF_CUSTOM_MERASMUS_ZAP = 59

---@type any
TF_CUSTOM_MERASMUS_DECAPITATION = 60

---@type any
TF_CUSTOM_CANNONBALL_PUSH = 61

