---@meta

-- Constants: E_ProjectileType
-- Auto-generated from: https://lmaobox.net/lua/Lua_Constants/
-- Last updated: 2025-12-05T10:33:23.988Z

---@type any
TF_PROJECTILE_NONE = 0

---@type any
TF_PROJECTILE_BULLET = 1

---@type any
TF_PROJECTILE_ROCKET = 2

---@type any
TF_PROJECTILE_PIPEBOMB = 3

---@type any
TF_PROJECTILE_PIPEBOMB_REMOTE = 4

---@type any
TF_PROJECTILE_SYRINGE = 5

---@type any
TF_PROJECTILE_FLARE = 6

---@type any
TF_PROJECTILE_JAR = 7

---@type any
TF_PROJECTILE_ARROW = 8

---@type any
TF_PROJECTILE_FLAME_ROCKET = 9

---@type any
TF_PROJECTILE_JAR_MILK = 10

---@type any
TF_PROJECTILE_HEALING_BOLT = 11

---@type any
TF_PROJECTILE_ENERGY_BALL = 12

---@type any
TF_PROJECTILE_ENERGY_RING = 13

---@type any
TF_PROJECTILE_PIPEBOMB_PRACTICE = 14

---@type any
TF_PROJECTILE_CLEAVER = 15

---@type any
TF_PROJECTILE_STICKY_BALL = 16

---@type any
TF_PROJECTILE_CANNONBALL = 17

---@type any
TF_PROJECTILE_BUILDING_REPAIR_BOLT = 18

---@type any
TF_PROJECTILE_FESTIVE_ARROW = 19

---@type any
TF_PROJECTILE_THROWABLE = 20

---@type any
TF_PROJECTILE_SPELL = 21

---@type any
TF_PROJECTILE_FESTIVE_JAR = 22

---@type any
TF_PROJECTILE_FESTIVE_HEALING_BOLT = 23

---@type any
TF_PROJECTILE_BREADMONSTER_JARATE = 24

---@type any
TF_PROJECTILE_BREADMONSTER_MADMILK = 25

---@type any
TF_PROJECTILE_GRAPPLINGHOOK = 26

---@type any
TF_PROJECTILE_SENTRY_ROCKET = 27

---@type any
TF_PROJECTILE_BREAD_MONSTER = 28

